name: py-modern
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - numpy=1.26.4
  - scipy=1.11.4
  - pandas=2.2.3
  - seaborn=0.13.2
  - matplotlib=3.8.4
  - scikit-learn=1.5.2
  - scikit-plot=0.3.7
  - hdbscan=0.8.38
  - umap-learn=0.5.6
  - scikit-bio=0.6.0
  - pytorch=2.3.1
  - torchvision=0.18.1
  - tensorboard=2.17.0
  - fastcluster
  - pip:
      - fcsparser==0.2.8
      - genieclust==1.1.6
      - wget
      - "https://github.com/gagolews/clustering-benchmarks/releases/download/v1.1.5/clustering_benchmarks-1.1.5.tar.gz"
      - "./dgcytof/DGCyTOF_Package"
